#!/bin/bash
#
# Specific functions for Homematic IP BSM hardware
#

##########
# Create
##########

function func_create_hmip_bsm() {

	# Template for this entity
	local l_template="hmip_bsm-lightswitch.yaml"

	# entity type
	local l_entityType="light"

	# suffix for this entity used in "name" and "unique_id"
	local l_sensorSuffix="777dimmer"

	# suffix for friendly_name used for UI
	local l_friendlyNameSuffix=""

	# define if entity is essential or nonessential to show up in UI
	local l_essentialforUIStatus="essential"

	local l_deviceChannel=${channel#*:}
	func_generateEntity


  # general homematic sensors
	# Kanal 0
	func_create_ghm_actualtemperature "nonessential" "0"
	func_create_ghm_actualtemperaturestatus "nonessential" "0"

	func_create_ghm_rssidevice "nonessential"
	func_create_ghm_rssipeer "nonessential"
	func_create_ghm_dutycycle "nonessential"
	func_create_ghm_unreach "nonessential"

	# Kanal 7
	func_create_hmip_bsm_current "essential"
	func_create_hmip_bsm_currentstatus "nonessential"
	func_create_hmip_bsm_energycounter "essential"
	func_create_hmip_bsm_energycounteroverflow "nonessential"
	func_create_hmip_bsm_frequency "essential"
	func_create_hmip_bsm_frequencystatus "nonessential"
	func_create_hmip_bsm_power "essential"
	func_create_hmip_bsm_powerstatus "nonessential"
	func_create_hmip_bsm_voltage "essential"
	func_create_hmip_bsm_voltagestatus "nonessential"
}



##########
# Extra functions
##########

# Channel 7
function func_create_hmip_bsm_current() {
	if [ $# -ne 1 ]; then
				 echo "func_create_hmip_bsm_current:"
				 echo "  missing essential status"
				 exit 1
	fi
	# Essential status (essential, nonessential)
	local l_essentialforUIStatus=$1

  local l_deviceChannel=7

  # Template for this entity
	local l_template="hmip_bsm-current.yaml"

	# entity type
  local l_entityType="sensor"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777current"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix="Strom"

  func_generateEntity

}

# Channel 7
function func_create_hmip_bsm_currentstatus() {
	if [ $# -ne 1 ]; then
				 echo "func_create_hmip_bsm_currentstatus:"
				 echo "  missing essential status"
				 exit 1
	fi
	# Essential status (essential, nonessential)
	local l_essentialforUIStatus=$1

	local l_deviceChannel=7

  # Template for this entity
	local l_template="hmip_bsm-currentstatus.yaml"

	# entity type
  local l_entityType="sensor"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777currentstatus"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix="Strom Status"

  func_generateEntity

}


# Channel 7
function func_create_hmip_bsm_energycounter() {
	if [ $# -ne 1 ]; then
				 echo "func_create_hmip_bsm_energycounter:"
				 echo "  missing essential status"
				 exit 1
	fi
	# Essential status (essential, nonessential)
	local l_essentialforUIStatus=$1

	local l_deviceChannel=7

  # Template for this entity
	local l_template="hmip_bsm-energycounter.yaml"

	# entity type
  local l_entityType="sensor"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777energycounter"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix="Energiezähler"

  func_generateEntity

}

# Channel 7
function func_create_hmip_bsm_energycounteroverflow() {
	if [ $# -ne 1 ]; then
				 echo "func_create_hmip_bsm_energycounteroverflow:"
				 echo "  missing essential status"
				 exit 1
	fi
	# Essential status (essential, nonessential)
	local l_essentialforUIStatus=$1

	local l_deviceChannel=7

  # Template for this entity
	local l_template="hmip_bsm-energycounteroverflow.yaml"

	# entity type
  local l_entityType="binary_sensor"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777energycounteroverflow"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix="Energiezähler Zählerüberlauf"

  func_generateEntity

}

# Channel 7
function func_create_hmip_bsm_frequency() {
	if [ $# -ne 1 ]; then
				 echo "func_create_hmip_bsm_frequency:"
				 echo "  missing essential status"
				 exit 1
	fi
	# Essential status (essential, nonessential)
	local l_essentialforUIStatus=$1

	local l_deviceChannel=7

  # Template for this entity
	local l_template="hmip_bsm-frequency.yaml"

	# entity type
  local l_entityType="sensor"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777frequency"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix="Frequenz"

  func_generateEntity

}

# Channel 7
function func_create_hmip_bsm_frequencystatus() {
	if [ $# -ne 1 ]; then
				 echo "func_create_hmip_bsm_frequencystatus:"
				 echo "  missing essential status"
				 exit 1
	fi
	# Essential status (essential, nonessential)
	local l_essentialforUIStatus=$1

	local l_deviceChannel=7

  # Template for this entity
	local l_template="hmip_bsm-frequencystatus.yaml"

	# entity type
  local l_entityType="sensor"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777frequencystatus"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix="Frequenz Status"

  func_generateEntity

}

# Channel 7
function func_create_hmip_bsm_power() {
	if [ $# -ne 1 ]; then
				 echo "func_create_hmip_bsm_power:"
				 echo "  missing essential status"
				 exit 1
	fi
	# Essential status (essential, nonessential)
	local l_essentialforUIStatus=$1

	local l_deviceChannel=7

  # Template for this entity
	local l_template="hmip_bsm-power.yaml"

	# entity type
  local l_entityType="sensor"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777power"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix="Leistung"

  func_generateEntity

}

# Channel 7
function func_create_hmip_bsm_powerstatus() {
	if [ $# -ne 1 ]; then
				 echo "func_create_hmip_bsm_powerstatus:"
				 echo "  missing essential status"
				 exit 1
	fi
	# Essential status (essential, nonessential)
	local l_essentialforUIStatus=$1

	local l_deviceChannel=7

  # Template for this entity
	local l_template="hmip_bsm-powerstatus.yaml"

	# entity type
  local l_entityType="sensor"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777powerstatus"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix="Leistung Status"

  func_generateEntity

}

# Channel 7
function func_create_hmip_bsm_voltage() {
	if [ $# -ne 1 ]; then
				 echo "func_create_hmip_bsm_voltage:"
				 echo "  missing essential status"
				 exit 1
	fi
	# Essential status (essential, nonessential)
	local l_essentialforUIStatus=$1

	local l_deviceChannel=7

  # Template for this entity
	local l_template="hmip_bsm-voltage.yaml"

	# entity type
  local l_entityType="sensor"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777voltage"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix="Spannung"

  func_generateEntity

}

# Channel 7
function func_create_hmip_bsm_voltagestatus() {
	if [ $# -ne 1 ]; then
				 echo "func_create_hmip_bsm_voltagestatus:"
				 echo "  missing essential status"
				 exit 1
	fi
	# Essential status (essential, nonessential)
	local l_essentialforUIStatus=$1

	local l_deviceChannel=7

  # Template for this entity
	local l_template="hmip_bsm-voltagestatus.yaml"

	# entity type
  local l_entityType="sensor"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777voltagestatus"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix="Spannung Status"

  func_generateEntity

}


