#!/bin/bash
#
# Specific functions for Homematic IP PS hardware
#

##########
# Create
##########

function func_create_hmip_psv4-switch() {

	# Template for this entity
	local l_template="hmip_ps-switch.yaml"

	# entity type
	local l_entityType="switch"

	# suffix for this entity used in "name" and "unique_id"
	local l_sensorSuffix="777switch"

	# suffix for friendly_name used for UI
	local l_friendlyNameSuffix=""

	# define if entity is essential or nonessential to show up in UI
	local l_essentialforUIStatus="essential"

	local l_deviceChannel=${channel#*:}
	func_generateEntity

	func_create_hmip_psv4-general

}

function func_create_hmip_psv4-general() {

  # general homematic sensors
	# Kanal 0
	func_create_ghm_actualtemperature "nonessential" "0"
	func_create_ghm_actualtemperaturestatus "nonessential" "0"

	func_create_ghm_rssidevice "nonessential"
	func_create_ghm_rssipeer "nonessential"
	func_create_ghm_dutycycle "nonessential"
	func_create_ghm_unreach "nonessential"
        func_create_ghm_configpending "nonessential" "0"
	func_create_ghm_errorcode "nonessential" "0"
	func_create_ghm_erroroverheat "nonessential" "0"
	func_create_ghm_operatingvoltage "nonessential"
	func_create_ghm_operatingvoltagestatus "nonessential" "0"

}

