#!/bin/bash
#
# Specific functions for Homematic IP eTRV2 hardware
#

##########
# Create
##########

function func_create_hmip_etrv2() {

	# Template for this entity
	local l_template="hmip_etrv2-radiatorvalve.yaml"

	# entity type
	local l_entityType="climate"

	# suffix for this entity used in "name" and "unique_id"
	local l_sensorSuffix="777radiator"

	# suffix for friendly_name used for UI
	local l_friendlyNameSuffix=""

	# define if entity is essential or nonessential to show up in UI
	local l_essentialforUIStatus="essential"

	local l_deviceChannel=${channel#*:}
	func_generateEntity


  # general homematic sensors

	func_create_ghm_operatingvoltage "nonessential"
	func_create_ghm_lowbat "essential"

	func_create_ghm_rssidevice "nonessential"
	func_create_ghm_rssipeer "nonessential"
	func_create_ghm_dutycycle "nonessential"
	func_create_ghm_unreach "nonessential"

	# specific sensors
	func_create_ghm_actualtemperature "nonessential" "1"
	func_create_ghm_actualtemperaturestatus "nonessential" "1"

	func_create_hmip_etrv2_boostmode "essential"
	func_create_hmip_etrv2_windowsstate "essential"
	func_create_hmip_etrv2_activeprofile "nonessential"
	func_create_hmip_etrv2_valvestate "nonessential"
	func_create_hmip_etrv2_level "nonessential"
	func_create_hmip_etrv2_levelstatus "nonessential"
	func_create_hmip_etrv2_setpointmode "nonessential"
	func_create_hmip_etrv2_setpointtemperature "nonessential"
	func_create_hmip_etrv2_frostprotection "nonessential"

	# create virtual sensors, actors and automations
	func_create_hmip_etrv2_automationvirtualhmclimatetopics "essential"

}


##########
# Extra functions
##########

## Channel 1
function func_create_hmip_etrv2_boostmode() {
	if [ $# -ne 1 ]; then
				 echo "func_create_hmip_etrv2_boostmode:"
				 echo "  missing essential status"
				 exit 1
	fi
	# Essential status (essential, nonessential)
	local l_essentialforUIStatus=$1

	local l_deviceChannel=1

  # Template for this entity
	local l_template="hmip_etrv2-boostmode.yaml"

	# entity type
  local l_entityType="switch"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777boostmode"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix="Boost Modus"

  func_generateEntity

}


function func_create_hmip_etrv2_windowsstate() {
	if [ $# -ne 1 ]; then
				 echo "func_create_hmip_etrv2_windowsstate:"
				 echo "  missing essential status"
				 exit 1
	fi
	# Essential status (essential, nonessential)
	local l_essentialforUIStatus=$1

	local l_deviceChannel=1

  # Template for this entity
	local l_template="hmip_etrv2-windowstate.yaml"

	# entity type
  local l_entityType="switch"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777windowstate"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix="Fenster Status"

  func_generateEntity

}


function func_create_hmip_etrv2_activeprofile() {
	if [ $# -ne 1 ]; then
				 echo "func_create_hmip_etrv2_activeprofile:"
				 echo "  missing essential status"
				 exit 1
	fi
	# Essential status (essential, nonessential)
	local l_essentialforUIStatus=$1

	local l_deviceChannel=1

  # Template for this entity
	local l_template="hmip_etrv2-activeprofile.yaml"

	# entity type
  local l_entityType="select"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777activeprofile"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix="Aktives Profil"

  func_generateEntity

}

# Sensor showing the current state of the valve
# @string subdirectory of the created sensor file
#
function func_create_hmip_etrv2_valvestate() {
	if [ $# -ne 1 ]; then
				 echo "func_create_hmip_etrv2_valvestate:"
				 echo "  missing essential status"
				 exit 1
	fi
	# Essential status (essential, nonessential)
	local l_essentialforUIStatus=$1

	local l_deviceChannel=1

  # Template for this entity
	local l_template="hmip_etrv2-valvestate.yaml"

	# entity type
  local l_entityType="sensor"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777valvestate"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix="Ventil Status"

  func_generateEntity

}

function func_create_hmip_etrv2_level() {
	if [ $# -ne 1 ]; then
				 echo "func_create_hmip_etrv2_level:"
				 echo "  missing essential status"
				 exit 1
	fi
	# Essential status (essential, nonessential)
	local l_essentialforUIStatus=$1

	local l_deviceChannel=1

  # Template for this entity
	local l_template="hmip_etrv2-level.yaml"

	# entity type
  local l_entityType="number"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777level"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix="Ventil-Öffnungsgrad"

  func_generateEntity

}

function func_create_hmip_etrv2_levelstatus() {
	if [ $# -ne 1 ]; then
				 echo "func_create_hmip_etrv2_levelstatus:"
				 echo "  missing essential status"
				 exit 1
	fi
	# Essential status (essential, nonessential)
	local l_essentialforUIStatus=$1

	local l_deviceChannel=1

  # Template for this entity
	local l_template="hmip_etrv2-levelstatus.yaml"

	# entity type
  local l_entityType="binary_sensor"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777levelstatus"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix="Ventil Status"

  func_generateEntity

}

function func_create_hmip_etrv2_setpointmode() {
	if [ $# -ne 1 ]; then
				 echo "func_create_hmip_etrv2_setpointmode:"
				 echo "  missing essential status"
				 exit 1
	fi
	# Essential status (essential, nonessential)
	local l_essentialforUIStatus=$1

	local l_deviceChannel=1

  # Template for this entity
	local l_template="hmip_etrv2-setpointmode.yaml"

	# entity type
  local l_entityType="sensor"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777setpointmode"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix="Modus"

  func_generateEntity

}

function func_create_hmip_etrv2_setpointtemperature() {
	if [ $# -ne 1 ]; then
				 echo "func_create_hmip_etrv2_setpointtemperature:"
				 echo "  missing essential status"
				 exit 1
	fi
	# Essential status (essential, nonessential)
	local l_essentialforUIStatus=$1

	local l_deviceChannel=1

  # Template for this entity
	local l_template="hmip_etrv2-setpointtemperature.yaml"

	# entity type
  local l_entityType="number"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777setpointtemperature"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix="Zieltemperatur"

  func_generateEntity

}

function func_create_hmip_etrv2_frostprotection() {
  if [ $# -ne 1 ]; then
    echo "func_create_hmip_etrv2_frostprotection:"
    echo "  missing essential status"
    exit 1
  fi
  # Essential status (essential, nonessential)
  local l_essentialforUIStatus=$1

  local l_deviceChannel=1

  # Template for this entity
  local l_template="hmip_etrv2-frostprotection.yaml"

  # entity type
  local l_entityType="binary_sensor"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777frostprotection"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix="Frostschutz"

  func_generateEntity

}


function func_create_hmip_etrv2_automationvirtualhmclimatetopics() {
  if [ $# -ne 1 ]; then
    echo "func_create_hmip_etrv2_automationvirtualhmclimatetopics:"
    echo "  missing essential status"
    exit 1
  fi
  # Essential status (essential, nonessential)
  local l_essentialforUIStatus=$1

  local l_deviceChannel=1

  # Template for this entity
  local l_template="hmip_etrv2-automationvirtualhmclimatetopics.yaml"

  # entity type
  local l_entityType="nonmqtt-automation"

  # suffix for this entity used in "name" and "unique_id"
  local l_sensorSuffix="777automationvirtualhmclimatetopics"

  # suffix for friendly_name used for UI
  local l_friendlyNameSuffix=""

  func_generateEntity


}


