#!/bin/bash
#
# Specific functions for Homematic IP KRC4 hardware
#


function func_create_hmip_krc4() {

	# TODO: MQTT Trigger would be better but only works with autodiscovery

#	# Template for this entity
#	local l_template="hmip_krc4-button1.yaml"
#
#	# entity type
#	local l_entityType="binary_sensor"
#
#	# suffix for this entity used in "name" and "unique_id"
#	local l_sensorSuffix="777motion"
#
#	# suffix for friendly_name used for UI
#	local l_friendlyNameSuffix=""
#
#	# define if entity is essential or nonessential to show up in UI
#	local l_essentialforUIStatus="essential"
#
#	local l_deviceChannel=${channel#*:}
#	func_generateEntity


  # general homematic sensors
	func_create_ghm_operatingvoltage "nonessential"
	func_create_ghm_lowbat "essential"

	func_create_ghm_configpending "nonessential" "0"
	func_create_ghm_rssidevice "nonessential"
	func_create_ghm_rssipeer "nonessential"
	func_create_ghm_dutycycle "nonessential"
	func_create_ghm_unreach "nonessential"
	func_create_ghm_errorcode "nonessential" "0"

}

